version: 0.2
  
phases:
  install:
    # Pre-requisites: git, curl unzip
    commands:
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - PATH=${PATH}:~/.tfenv/bin
      - tfenv install
  build:
    commands:
      - terraform init
      - terraform plan
      - terraform apply
